[project]
name = "kipack"
version = "1.0.0"
description = "A python-based solver for kinetic equations"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "absl-py>=2.2.2",
    "jax[cuda]>=0.5.3",
    "matplotlib>=3.10.1",
    "ml-collections>=1.0.0",
    "numpy>=2.2.4",
    "pyfftw>=0.15.0",
    "scipy>=1.15.2",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[dependency-groups]
dev = [
    "clawpack>=5.11.0",
 "jupyter>=1.1.1",
 "pre-commit>=4.2.0",
]
